/**
 * @file    ReaderCapabilities.h
 * @brief	Definitions for reader device capabilities
 */

#ifndef READERCAPABILITIES_H_
#define READERCAPABILITIES_H_

#define CAP_IANAPEN 123451
#define CAP_MODEL_NAME 123452
static const char CAP_FIRMWARE_VER_STR[] = "Firmware Version";
#define CAP_MAX_ANTENNAS 9
#define CAP_CAN_SET_ANTENNA_PROPERTIES 0
#define CAP_ALLOW_CONTROL_OF_RECEIVE_SENSITIVITY 0

#define CAP_CAN_DO_RFSURVEY 0
#define CAP_CAN_DO_TAG_INVENTROY_STATE_AWARE_SINGULATION 0
#define CAP_CAN_REPORT_BUFFER_FILL_WARNING 0
#define CAP_MAX_NUM_ROSPECS 32
#define CAP_MAX_NUM_SPECS_PER_ROSPEC 8
#define CAP_MAX_NUM_INV_PAR_SPECS_PER_AISPEC 4
#define CAP_MAX_PRIORITY_LEVEL_SUPPORTED 1
#define CAP_MAX_NUM_ACCESSSPECS 32
#define CAP_MAX_NUM_OPSPECS_PER_ACCESSSPEC 8
#define CAP_SUPPORTS_CLIENT_REQUEST_OPSPEC 0
#define CAP_CLIENT_REQUEST_OPSPEC_TIMEOUT 0
#define CAP_SUPPORTS_EVENT_AND_REPORT_HOLDING 0

#define CAP_COUNTRY_CODE 82
#define CAP_COMM_STANDARD 9

#define CAP_CAN_SUPPORT_BLOCKERASE 0
#define CAP_CAN_SUPPORT_BLOCKWRITE 0
#define CAP_CAN_SUPPORT_BLOCKPERMALOCK 0
#define CAP_CAN_SUPPORT_TAGRECOMMISSIONING 0
#define CAP_CAN_SUPPORT_UMIMETHOD2 0
#define CAP_CAN_SUPPORT_XPC 0
#define CAP_MAX_NUM_SELECT_FILTERS_PER_QUERY 0


#endif /* READERCAPABILITIES_H_ */
